### ISSUE TITLE
Creating different step for each brick

### ISSUE THREAD

**Issue by andreid11** [LasseD/brickgraphics#13]
After exporting a mosaic to ldraw the building of the project with LEGO bricks is made out of steps. But one step is made out of 16 bricks. If y make a 48x48 mosaic the generated ldraw file has 144 steps and 2304 parts.
It will be useful that the export will generate a ldraw file that will have a step for each individual brick. Like, for a 48x48 mosaic the file will have 2304 steps (and of course 2304 parts).

**Comment by LasseD** [comment]
If you click on the button with the magnifying glass, then the right side turns into the step view. Click the double-arrow buttons to change the size of each step (or use the keyboard shortcuts).

Did this solve your problem?

**Comment by andreid11** [comment]
Yes, this is what I was looking for. I tested now the solution and it works great. 
Now I can make one step for each stud.
Thanks.
